# Generated by Django 4.1.7 on 2023-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_forgetpassword_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgetpassword',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='otp',
            field=models.IntegerField(),
        ),
    ]
